# Generated by Django 4.2.7 on 2023-11-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.DateTimeField()),
                ('cv', models.CharField(max_length=20)),
                ('bag_seal_id', models.CharField(max_length=20)),
                ('cage_id', models.CharField(max_length=20)),
            ],
        ),
    ]
