# Generated by Django 4.2.5 on 2023-12-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_id', models.CharField(max_length=255, unique=True)),
                ('grid_code', models.IntegerField(max_length=10, unique=True)),
            ],
        ),
    ]
