# Generated by Django 4.1 on 2023-12-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0002_alter_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='bag_seal_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
