# Generated by Django 4.2.5 on 2023-12-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0002_bags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='grid_code',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
