# Generated by Django 4.1 on 2023-12-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0003_alter_data_bag_seal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_id', models.CharField(max_length=50, unique=True)),
                ('cage_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
