# Generated by Django 4.2.5 on 2023-12-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0003_cage_grid_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bags',
            name='grid_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cage',
            name='grid_code',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
