# Generated by Django 4.2.5 on 2023-12-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0004_alter_bags_grid_code_alter_cage_grid_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bags',
            name='grid_code',
            field=models.CharField(max_length=10),
        ),
    ]
