# Generated by Django 4.1 on 2023-12-21 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0005_rename_status_cage_is_occupied_remove_cage_cage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='cage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagtrac.cage'),
        ),
    ]
