# Generated by Django 4.1 on 2023-12-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0005_alter_bags_grid_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bags',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bagtrac.cage'),
        ),
        migrations.AlterField(
            model_name='cage',
            name='grid_code',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
