# Generated by Django 4.1 on 2023-12-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0006_alter_data_cage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cage',
            old_name='cage_id',
            new_name='cage_name',
        ),
    ]
