# Generated by Django 4.1 on 2023-12-26 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0006_bags_cage_alter_cage_grid_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_created', models.BooleanField(default=False)),
                ('bag_label_generated', models.BooleanField(default=False)),
                ('recieved_at_cv', models.BooleanField(default=False)),
                ('put_in_grid', models.BooleanField(default=False)),
                ('put_out_grid', models.BooleanField(default=False)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagtrac.bags')),
            ],
        ),
    ]
