# Generated by Django 4.2.5 on 2023-12-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0008_bags_bag_created_bags_bag_label_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ibbags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.DateTimeField(auto_now_add=True)),
                ('bag_id', models.CharField(max_length=255, unique=True)),
                ('user', models.CharField(max_length=255)),
                ('cage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagtrac.cage')),
            ],
        ),
    ]
