# Generated by Django 4.2.5 on 2023-12-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0009_ibbags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibbags',
            name='cage_id',
            field=models.CharField(max_length=255),
        ),
    ]
