# Generated by Django 4.2.5 on 2023-12-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0010_alter_ibbags_cage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibbags',
            name='bag_id',
            field=models.CharField(max_length=255),
        ),
    ]
