# Generated by Django 4.2.5 on 2023-12-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0011_alter_ibbags_bag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=10)),
                ('cage_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bagtrac.cage')),
            ],
        ),
        migrations.AddField(
            model_name='cage',
            name='grid_area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bagtrac.gridarea'),
        ),
    ]
