# Generated by Django 4.2.5 on 2023-12-30 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0012_gridarea_cage_grid_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridarea',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
