# Generated by Django 4.2.5 on 2023-12-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0013_gridarea_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridarea',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
