# Generated by Django 4.2.5 on 2023-12-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0016_remove_gridarea_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='cage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bagtrac.cage'),
        ),
    ]
