# Generated by Django 4.2.5 on 2024-01-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0018_bags_seal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BNRBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.DateTimeField(auto_now_add=True)),
                ('bag', models.CharField(max_length=255)),
                ('recieved', models.BooleanField(default=False)),
            ],
        ),
    ]
