# Generated by Django 4.2.5 on 2024-01-04 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0019_bnrbag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bags',
            name='time1',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
