# Generated by Django 4.2.9 on 2024-01-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0020_bags_time1'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.CharField(max_length=255)),
                ('ptc', models.CharField(max_length=255)),
            ],
        ),
    ]
