# Generated by Django 4.2.9 on 2024-01-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagtrac', '0021_ptc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptc',
            name='grid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ptc',
            name='ptc',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
