name: bagtrac_deployment

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use SSH key for deployment
        uses: appleboy/ssh-action@master
        with:
          host: 15.207.115.205
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/bagtrac
            git pull origin prod && python3 manage.py makemigrations && python3 manage.py migrate
